### ISSUE TITLE
Can't get the player element

### ISSUE THREAD

**Issue by haarp** [sebaro/ViewTube#11]
Good day,

as of a few hours ago, ViewTube stopped working on Youtube. Every video is affected. Google must've changed something, as youtube-dl is also broken.

Browser: Firefox 54, Greasemonkey 3.11, Viewtube from today (downloaded just now)

**Comment by sebaro** [comment]
The update works with the new YouTube design only.

Go to youtube.com/new and enable the new design.

Or if you still want to use the old one use the previous version:
https://raw.githubusercontent.com/sebaro/ViewTube/531c2224b05fc92bef6dd9e1a4a2f0d03da8bbcd/viewtube.user.js

**Comment by haarp** [comment]
Ah I see, thanks.

But it should be considered a regression when functionality breaks with a new version, even if it's intentional.

**Comment by sebaro** [comment]
For now I can't support both designs, so yes, is broken for the old design and the previous script's version is broken for the new design.

**Comment by haarp** [comment]
Things seem to be working on my end for a while now. Thanks for your support!
