### ISSUE TITLE
Unable to extract most tracks

### ISSUE THREAD

**Issue by birdie-github** [sebaro/ViewTube#18]
https://youtu.be/o6XE_czm778

Using:
SaveTube 2018.01.10
Firefox 52 ESR
GreaseMoneky 3.17

**Comment by birdie-github** [comment]
After a few refreshes it worked.

**Comment by sebaro** [comment]
What does extract mean, download?

**Comment by birdie-github** [comment]
I meant I opened the page and I could see only 4 download options vs. at least 8 to 10 which your script provides for HD videos. Anyways, everything worked as expected after I refreshed the page twice. I'm sorry for the noise.
