### ISSUE TITLE
How this compared to Tobias Rupf's fork? What about merging them?

### ISSUE THREAD

**Issue by timofonic** [sebaro/ViewTube#4]
Hello.

Could it be possible to merge both forks into one?

https://greasyfork.org/en/scripts/1203-viewtube-gm

Kind regards.

**Comment by sebaro** [comment]
Hi,

You can see the differences on the script's page.

Tobias added some features that are not supported by all browsers.

You can try both and use the one that works better for you, forking is a good thing, you have options.
