### ISSUE TITLE
subtitles support

### ISSUE THREAD

**Issue by mrkapqa** [sebaro/ViewTube#5]
Hello ,

have asked this in the past but forgot about how to do it correctly so please if you dont mind

can you please show the proper way on how to enable subtitle playback for youtube 

i am using linux, and maybe the distro does no longer provide good subtitle plugins,
could not get it to function<

have tried several options, would not function.

i am using firefox-esr as offered by devuan
distro is devuan 5.0 , source packages should probably be from debian 12.

thank you sebaro.

this is reference video i  tried.
https://www.youtube.com/watch?v=wiDYVVKAh00

**Comment by sebaro** [comment]
Added subtitles fix in test version:
https://github.com/sebaro/ViewTube/raw/master/viewtubetest.user.js

Select the subtitles language in the options panel.

**Comment by mrkapqa** [comment]
i have tried with several computer but could not get it to play subtitles on ubuntu/devuan/osx

probably i have wrong settings or missing plugins?

the subtitle selection i made is "en" for english?


only if i select "embed video with "video" ..." do i get in the playback video on the right of the timeline a "CC" logo indicator, but subtitles are not shown nevertheless

like here

![Screenshot from 2024-01-09 11-25-33](https://github.com/sebaro/ViewTube/assets/12947465/fd46e7e0-416f-43f3-9ddc-255f8f9c97da)

![Screenshot from 2024-01-09 11-25-47](https://github.com/sebaro/ViewTube/assets/12947465/be88f1d2-2e2e-4c7f-8df7-e53c696b8757)

**Comment by sebaro** [comment]
Did you install the test version, 2024.01.09?

**Comment by mrkapqa** [comment]
yes, the one from link above you provided. last updated 1/9/2024

**Comment by sebaro** [comment]
Added more fixes, same link above.

**Comment by mrkapqa** [comment]
thank you very much,

this now functiuons beautifully, windows, macos, linux, very happy.
