### ISSUE TITLE
Can you please add Kodi as player?

### ISSUE THREAD

**Issue by timofonic** [sebaro/ViewTube#6]
Hello.

I use Kodi on my media center and other computer systems. I would love send videos to Kodi, but "send to Kodi" Firefox extension doesn't work with Pale Moon.

It would be amazing if I can click an icon or select the player in your great javascript scripts and be able to play the videos on Kodi :D

Kind regards.

**Comment by sebaro** [comment]
Kodi has YouTube, Dailymotion, Vimeo etc. addons, why don't you use those?

Did you tried to install the extension on Palemoon using its liink:
https://addons.mozilla.org/firefox/downloads/latest/421038/addon-421038-latest.xpi?src=dp-btn-primary

**Comment by timofonic** [comment]
@sebaro 
I want to be able to play the videos on Kodi too. I tried that extension, it's not compatible with Pale Moon.

Sorry for not explaining it correctly from the beginning...

**Comment by sebaro** [comment]
The script doesn't use any video players, the browser dose.
When you use 'Play' the browser will use an video plugin if it finds one.
When you use 'Get' the browser will download the video or use an external application.
If you don't want the browser to download the video, go to 'Preferences -> Applications', search the media type then select the application you want from 'Action'.
